# Generated by Django 6.1.1 on 2026-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='nome_aluno',
            new_name='nome_responsavel',
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_devolucao',
            field=models.TimeField(default='23:59:00'),
            preserve_default=False,
        ),
    ]
