# Generated by Django 6.1.1 on 2026-09-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_nome_aluno_reserva_nome_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Recusada', 'Recusada'), ('Concluída', 'Concluída')], default='Pendente', max_length=20),
        ),
    ]
